# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 535719b1c25bcd4853d0f8e67d180a17b726140294c3f5ef60ae6276f4f1f84a878a5a46207abca7f487fa47639b666036feaa6dbc60ff4419e7502e2bbe5f19

test:
  secret_key_base: 5039f02a94c6fde683fdf3bb21c83c1bacec42a2f6a4336f40e7674ce056092c693474f3a8b688cb273b182ebb9aa79605cc479070fc1817847b3e7c38eb013c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
